### ISSUE TITLE
More likes than views

### ISSUE THREAD

**Issue by therealharpaljadeja** [mehulkar/mehulkar.com#97]
Not sure how...

<img width="222" alt="image" src="https://github.com/mehulkar/mehulkar.com/assets/38040789/e2e30863-6d7b-45c2-a0cb-2b39ed2bb23a">

**Comment by mehulkar** [comment]
I implemented views after I implemented social media likes, so it didn't start counting views until very recently! (and I'm not even sure social media likes are working anymore)
